# Generated by Django 4.0.6 on 2022-08-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='account',
        ),
    ]
