# Generated by Django 4.0.6 on 2022-08-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_remove_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
    ]
