# Generated by Django 4.0.6 on 2022-08-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_remove_thirdparty_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
    ]
