# Generated by Django 4.0.6 on 2022-08-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0007_remove_card_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_ref',
        ),
    ]
